apiVersion: v1
kind: PersistentVolume
metadata:
  name: provider-path
spec:
  capacity:
    storage: 500Mi  # The size of the volume
  accessModes:
    - ReadWriteOnce  # Access mode should match the PVC
  hostPath:
    path: /home/ubuntu/helm-chart-keycloak/providers  # The path on the host machine
    type: DirectoryOrCreate  # Ensures directory is created if it does not exist
