apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: keycloak-pvc
spec:
  accessModes:
    - {{ .Values.keycloak.persistence.accessMode }}
  resources:
    requests:
      storage: {{ .Values.keycloak.persistence.size }}