apiVersion: v1
kind: Secret
metadata:
  name: keycloak-secret
stringData:
  KEYCLOAK_ADMIN: {{ .Values.keycloak.adminUser }}
  KEYCLOAK_ADMIN_PASSWORD: {{ .Values.keycloak.adminPassword }}
  POSTGRES_USER: {{ .Values.postgresql.user }}
  POSTGRES_PASSWORD: {{ .Values.postgresql.password }}
